name: conditional_builder
description: Synchronous conditional widget renderer.
version: 2.0.0
author: Frederick Corcino Alejo<frederickcorcino@gmail.com>
homepage: https://github.com/frederickcxa/conditional_builder

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
